### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Elsie19** [mina-atef-00/linux-learning#1]
https://github.com/mina-atef-00/linux-learning/blob/4b107946c8f01e51770a63fcfbd29e55b11ae8a2/bash-scripting/arrays#L10

It does *not* print out all elements, just the first:
![image](https://user-images.githubusercontent.com/58742515/227408824-431d9c8f-fc60-4903-9ee8-09cb969377ee.png)
You probably want `${my_arr[*]}"` to print out all the elements as a string.
![image](https://user-images.githubusercontent.com/58742515/227409870-82bd8fc5-3ac2-4cdf-ab47-06148604cf2e.png)

---

Same for this line:
https://github.com/mina-atef-00/linux-learning/blob/4b107946c8f01e51770a63fcfbd29e55b11ae8a2/bash-scripting/loops#L19
![image](https://user-images.githubusercontent.com/58742515/227408905-a6c3c31a-1e7d-477a-b11f-e26c7527e938.png)

You want this:
```bash
while IFS= read -r -n1 char; do
#      ^            ^-- Read character by character
#      |-- IFS is unset, meaning to read word by word
  echo "$char"
done <<< "Hello"
#     ^-- Read by string into while loop
```

---

This can be turned into `$((1 + 4))`, and the next line can be `$((1 * 4))` instead of using an external command and escaping a character:
https://github.com/mina-atef-00/linux-learning/blob/4b107946c8f01e51770a63fcfbd29e55b11ae8a2/bash-scripting/basics#L8

---

Another issue I saw was your use of `set -e`. While this might seem like a good issue, consider this piece of code:

```bash
if [[ -d /foo ]]; then ...; else ...; fi
```

The intent of this `[[ -d /foo ]]` is that it fails, and the if statement will run the else part, however `set -e` will simply stop the program because `[[ -d /foo ]]` returns a non 0 return code.

`set -e` will make it so that *every single command* that returns a non-zero exit code will fail, fullstop, even if you are testing for the non-zero exit code. My advice is to remove it, but be hyper aware of the situations where it could go wrong and add checks for those.

---

You are also using single brackets (`[`), which is not recommended for use in Bash, where the double bracket (`[[`) is the safer and more feature rich option, with features like the ability to not quote the left part of the comparison, regex, you don't have to escape characters like `>`,

**Comment by mina-atef-00** [comment]
Thanks so much for the valuable info!

**Comment by mina-atef-00** [comment]
@Henryws what's your opinion on using `grep -o .` instead of `read` for looping through characters in a string?
```sh
for char in $(grep -o "." <<<"hello"); do
    echo "$char"
done
```

**Comment by Elsie19** [comment]
`read` is a builtin, so it's *much* faster than using grep. If it's a long string, then use grep, as it will be faster to print out every character into a loop, whereas `read` will read character by character, rather than all at once, so the comparison is really apples and oranges.

### Benchmarks
`test.sh` is using `read`, `test1.sh` is using grep.
![image](https://user-images.githubusercontent.com/58742515/227728549-5e183e6e-bc8d-4b4a-82a1-48625365a866.png)
